# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fecha',
            field=models.DateField(default='2018-05-07'),
        ),
    ]
