# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180510_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fecha',
            field=models.DateField(default='2018-05-11'),
        ),
    ]
