# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
        migrations.AlterField(
            model_name='register',
            name='sex',
            field=models.CharField(choices=[('F', 'Mujer'), ('M', 'Hombre'), ('U', 'Otro')], max_length=1),
        ),
    ]
