# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0002_auto_20180320_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birthday',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='register',
            name='emiil',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='register',
            name='sex',
            field=models.CharField(choices=[('F', 'Mujer'), ('M', 'Hombre'), ('U', 'Otro')], max_length=1, verbose_name='Género'),
        ),
    ]
