# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0003_auto_20180507_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Ciudad'),
        ),
    ]
