# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0004_auto_20180510_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
